# Generated by Django 3.1.3 on 2020-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='default_user_img',
            field=models.FileField(upload_to='users/files', verbose_name='Users using default image'),
        ),
    ]
