# Generated by Django 3.1.3 on 2020-12-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201216_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='note',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='search',
            name='username',
            field=models.CharField(max_length=200, null=True, verbose_name='Username'),
        ),
    ]
