# Generated by Django 3.1.3 on 2020-12-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
