# Generated by Django 3.1.3 on 2020-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_search_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='is_finished',
            field=models.BooleanField(default=False, null=True, verbose_name='Finished'),
        ),
    ]
